### ISSUE TITLE
[求教]: format 参数怎么使用?

### ISSUE THREAD

**Issue by hotmanga** [hungtcs/clunarc#1]
我阅读 `--help` 里有提示使用 `--format` 参数格式. 但是我使用了如下几种都没有展示:

```bash
$> clunarc --format 2022-12-01
$> clunarc -f 2022-12-01
```

以上两种似乎都不行. 我看首页截图示例里也没有. 
请求正确做法可以是?

**Comment by hungtcs** [comment]
@hotmanga 哈喽，`clunar` 可以接收一个参数来展示指定公历日期所对应的农历日期，比如可以使用`clunarc 2022-12-10` 来查看2022年12月10日的农历日期，或者`clunarc month 2022-10` 来查看2022年10月的月历。

`--format`其实是为用户输入的日期字符串指定格式以便clunarc能够解析（使用moment解析），但是大部分情况下都可以自动正确解析，此参数针对输入而不是输出。
